site_name: Ilorm documentation
pages:
    - Home: index.md
    - Api: api.md
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'light blue'
repo_name: 'stombre/ilorm'
repo_url: 'https://github.com/stombre/ilorm'
