site_name: Ilorm documentation
nav:
    - Home: index.md
    - Quick start: quick_start.md
    - API:
        - Core: api/core.md
        - Model: api/model.md
        - Model_Id: api/model_id.md
        - Query: api/query.md
        - Schema: api/schema.md
        - Field: api/fields.md
        - Transaction: api/transaction.md
    - Advanced:
        - Create connector: advanced/create_connector.md
        - Create a plugin: advanced/create_plugin.md
    - Connectors:
        - Intro: connectors/intro.md
        - Knex: connectors/knex.md
        - MongoDB: connectors/mongodb.md
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'light blue'
repo_name: 'ilorm'
repo_url: 'https://github.com/ilorm/core'
docs_dir: 'source'
site_dir: 'docs'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
